services:
  exchange-rate-api:
    build:
      context: ./API/exchange-rate-api
    ports:
      - "3002:3002"
    container_name: exchange-rate-api-service
    networks:
      - backend

  gold-api:
    build:
      context: ./API/gold-api
    ports:
      - "3001:3001"
    container_name: gold-api-service
    networks:
      - backend

  monitor:
    build:
      context: ./monitor
    ports:
      - "8020:8020"
    container_name: monitor-service
    networks:
      - backend

networks:
  backend:
